language: python
python:
  - '3.8'

env: DJANGO_SETTINGS_MODULE="config.settings.local"

# command to install dependencies
install:
  - pip install -r requirements/local.txt

services:
  - postgresql

script:
  - pytest
  - black . --check
  - isort . --check